#! /usr/bin/env python
import sys
if len(sys.argv) == 1:
    print 'syntax: darkall imageName'
else:
    import numpy as np
    import pylab as pl
    import pyfits as pf
    hdu=pf.open(sys.argv[1])
    nn=len(hdu)
    print '----extension---Position---darkL (ADU)---darkR (ADU)'
    for i in range(1,nn):
        b=pf.getdata(sys.argv[1],i)
        hdr=pf.getheader(sys.argv[1],i)
        darkL=np.mean(b[1500:2000,400:440])-np.mean(b[1500:2000,10:50])
        darkR=np.mean(b[1500:2000,1400:1440])-np.mean(b[1500:2000,2110:2150])
        print i,'---',hdr['detpos'],'----',darkL,'----',darkR
