#! /usr/bin/env python
import sys
if len(sys.argv) == 1:
    print 'syntax: noise imageName extension'
else:
    import numpy as np
    import pylab as pl
    import pyfits as pf
    b=pf.getdata(sys.argv[1],int(sys.argv[2]))
    noiseL=np.std(b[2000:2500,10:50])
    bins=np.unique(b[2000:2500,10:50])
    fig=pl.figure(figsize=(15,8))
    ax=fig.add_subplot(1,2,1)
    pl.hist(b[2000:2500,10:50].flatten(),bins=bins,facecolor='green')
    pl.xlabel('Counts (ADU)')
    pl.text(0.2,0.8,'noise: '+str(np.round(noiseL,4))+'(ADU)',transform = ax.transAxes)
    pl.title('Left: Noise')
    print '----- Left noise is: '+str(noiseL)+' -----'
    ax=fig.add_subplot(1,2,2)
    noiseR=np.std(b[2000:2500,2110:2150])
    bins=np.unique(b[2000:2500,2110:2150])
    pl.hist(b[2000:2500,2110:2150].flatten(),bins=bins,facecolor='orange')
    pl.xlabel('Counts (ADU)')
    pl.text(0.2,0.8,'noise: '+str(np.round(noiseR,4))+'(ADU)',transform = ax.transAxes)
    pl.title('Right: Noise')
    print '----- Right noise is: '+str(noiseR)+' -----'
    pl.show()
    
